# Generated by Django 5.2.5 on 2025-10-08 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_galleryimage'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='galleryimage',
            new_name='app_gallery_page_ke_036737_idx',
            old_name='app_galler_page_ke_6d3b23_idx',
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
