from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_key', models.CharField(db_index=True, max_length=128, verbose_name='Ключ страницы')),
                ('block_key', models.CharField(db_index=True, max_length=128, verbose_name='Ключ блока')),
                ('content', models.TextField(blank=True, default='', verbose_name='Контент (HTML/Markdown/текст)')),
                ('content_type', models.CharField(choices=[('text', 'Текст'), ('html', 'HTML'), ('markdown', 'Markdown')], default='text', max_length=32, verbose_name='Тип контента')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.adminuser', verbose_name='Кем обновлено')),
            ],
            options={
                'verbose_name': 'Блок контента',
                'verbose_name_plural': 'Блоки контента',
                'unique_together': {('page_key', 'block_key')},
            },
        ),
        migrations.AddIndex(
            model_name='contentblock',
            index=models.Index(fields=['page_key', 'block_key'], name='app_conten_page_ke_6e0a0a_idx'),
        ),
    ]

# Generated by Django 5.2.5 on 2025-10-03 20:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_key', models.CharField(db_index=True, max_length=128, verbose_name='Ключ страницы')),
                ('block_key', models.CharField(db_index=True, max_length=128, verbose_name='Ключ блока')),
                ('content', models.TextField(blank=True, default='', verbose_name='Контент (HTML/Markdown/текст)')),
                ('content_type', models.CharField(choices=[('text', 'Текст'), ('html', 'HTML'), ('markdown', 'Markdown')], default='text', max_length=32, verbose_name='Тип контента')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Кем обновлено')),
            ],
            options={
                'verbose_name': 'Блок контента',
                'verbose_name_plural': 'Блоки контента',
                'indexes': [models.Index(fields=['page_key', 'block_key'], name='app_content_page_ke_bdabc5_idx')],
                'unique_together': {('page_key', 'block_key')},
            },
        ),
    ]
