# Generated by Django 5.2.5 on 2025-10-21 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_app_galler_page_ke_6d3b23_idx_app_gallery_page_ke_036737_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactrequest',
            name='email_sent',
            field=models.BooleanField(default=False, verbose_name='Email отправлен'),
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='email_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время отправки email'),
        ),
    ]
